#server:
#  port: 3366
#
#spring:
#  application:
#    name: config-client
#  cloud:
#    config:
#      label: master
#      name: config
#      profile: dev
#      uri: http://localhost:3344
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka
#  instance:
#    hostname: eureka7001.com
#    #暴露服务
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
