server:
  port: 8001

spring:
  application:
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/bay?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.team.springcloud.entities

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: payment8001  #配置别名
    prefer-ip-address: true
    #http://localhost:7001/eureka单机版
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是9lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 100
    lease-expiration-duration-in-seconds: 200